chromatic = true

min_scrolls = 5

hide_evasion = true

chancing_bases = [
  "Champion Kite Shield",
  "Ezomyte Dagger",
  "Fiend Dagger",
  "Prophecy Wand",
]

min_drop_lvl_bases = 70
good_bases = [
  "Pig-Faced Bascinet",
  "Full Dragonscale",
  "Dragonscale Gauntlets",
  "Cardinal Round Shield",
  "Hubris Circlet",
  "Crusader Gloves",
  "Murder Mitts",
  "Archon Kite Shield",
  "Champion Kite Shield",
]
rare_gear_min_ilvl = 78
crafting_bases_min_ilvl = 80

flask_min_quality = 10
flask_min_ilvl = 82

bad_cards = [
  "Destined to Crumble",
  "Lantador's Lost Love",
  "Prosperity",
  "Struck by Lightning",
  "The Carrion Crow",
  "The Hermit",
  "The King's Blade",
  "The Lover",
  "The Metalsmith's Gift",
  "The Opulent",
  "The Scarred Meadow",
  "The Warden",
  "Thunderous Skies",
]
good_cards = ["The Apothecary"]
