name = "lootfilter"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 1.1.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
